### ISSUE TITLE
No hdf5.h file

### ISSUE THREAD

**Issue by SunshineDou** [yindaz/DeepCompletionRelease#10]
Hello, When I cd into the gaps directory, and make, it report error:
depth2depth error: hdf5:No such file or directory.
I have seen #5 ,but I still can't understand  how to modify it. could you please help me ?
Thank you very much

**Comment by SunshineDou** [comment]
I have add hdf5/include and hdf5/lib as follows, but it still report errors
![hdf5](https://user-images.githubusercontent.com/25578572/50054003-17e38200-0178-11e9-9dab-926110069e13.png)
![hdf5_2](https://user-images.githubusercontent.com/25578572/50054005-19ad4580-0178-11e9-832d-310dd2716972.png)
Thanks very much

**Comment by SunshineDou** [comment]
I have solved it

**Comment by JiangWenPL** [comment]
@SunshineDou Hi, I have got the same issue too.  Could you tell me how to solve it?

**Comment by xjtucx** [comment]
hello,could you please tell me how to solve this question?
thank you very much！
