### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Mikeraka** [yindaz/DeepCompletionRelease#13]
Hello,
I am very interested in your dataset, I have download the agreement file of the SUNCG-RGBD, MatterPort3D, Scannet, print them and signatured on it(except the PI's name and PI's email, as I don't know the PI's meaning). I scanned the agreement files and sent them to the  organizers, which it's nearly 4 days, but I get no response until now. could you please tell me is there any problem or I should wait patiently?
Thank you very much

**Comment by yindaz** [comment]
Sorry I didn't catch the email. Could you send me an email including all
these docs again? Thanks!

**Comment by Mikeraka** [comment]
@yindaz your email address is yindaz@cs.princeton.edu, is it right?
as I send it in this address, but it was bounced, I cannot send the email.

**Comment by yindaz** [comment]
Yes, the email is correct. I double checked the email and seems it's okay
to send email to it from gmail. Please also try yindaz@gmail.com if you
couldn't make it through.

**Comment by Mikeraka** [comment]
@yindaz Thank you very much. I have sent the email using yinda@gmain.com successfully

**Comment by yindaz** [comment]
Make sure you send it to yindaz at gmail dot com.

**Comment by Mikeraka** [comment]
@yindaz Thank you very much for your replying
Yeah,I have sent it successfully as follow picture shows, but I received no reply. What's the matter?
![2019-01-03 09-51-39](https://user-images.githubusercontent.com/45626438/50578352-08508280-0e74-11e9-8dfe-bdac48bc8835.png)
