### ISSUE TITLE
Method - Optimization

### ISSUE THREAD

**Issue by 94929** [yindaz/DeepCompletionRelease#14]
Hi, I would like to see how 3.4. Optimization is done in the code.
According to README, it looks like depth2depth.cpp under ./gaps/apps directory contains the code.
However, I'm not sure where E is formed in the file.
I would appreciate if you could tell me where E is formed.
Thanks in advance.

**Comment by yindaz** [comment]
Please see CreateDepthImage function for more details.

**Comment by 94929** [comment]
Sorry for re-opening the issue, I might be asking a naive question.
Since I'm new to Computer Vision, I'm not sure how the global optimization process works.

Specifically, in 3.4 Optimization, 
* I have the surface normal image N and occlusion boundary image B ready
* Then I'm trying to construct the objective function E
* But I'm not sure how each term E_D, E_N and E_S are constructed

Thus, I would appreciate if you could provide me a reference (or example, if possible) of such optimization process.

(I'm trying to implement the paper in PyTorch)

**Comment by xjtucx** [comment]
Hi, have you solved your question?
I want to learn this method of the global optimization so i read  depth2depth.cpp, but i still have some questions.
Could you tell me your thinking?
Thanks in advance.
