### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by Mikeraka** [yindaz/DeepCompletionRelease#15]
Hello, I want to evaluate the performance of the depth completion of my own dataset. I know I should use the evalDepth.m file. the input is result_folder, dataset and suffix. I wonder what's the suffix? is it  the test file in /torch/data_list as follow picture shows?
![2019-01-10 10-15-05](https://user-images.githubusercontent.com/45626438/50941641-a53c9c80-14c0-11e9-97a0-70caff64bb80.png)

I open the scannet_test_list_small.txt file, the content in it is as follows:
scene0144_01/data_dir/000000128_suffix
scene0678_02/data_dir/000001472_suffix
scene0643_00/data_dir/000000128_suffix
scene0580_00/data_dir/000003975_suffix
scene0591_01/data_dir/000000480_suffix
scene0606_01/data_dir/000001843_suffix
scene0011_01/data_dir/000001952_suffix
scene0609_00/data_dir/000000160_suffix
what does this mean in it? and I want to know how to generate the file to evaluate the performance?
Thank you very much!

**Comment by yindaz** [comment]
It is just a way to list data and leave a pattern that is easy to detect and replace.

**Comment by SunshineDou** [comment]
@yindaz Thank you very much for your replying. I have got it. but I want to know what should I do if I want to evaluate on my own dataset result?  in the evalDepth.m file, there are two lines as follows:
 raw = testdata(a).raw;
 gdt = testdata(a).gdt;

the raw is the original data, right? but what's the gdt? how to get it? 
I have also download the "scannet_normal" and "matterport_normal" in the pre_calc_result folder, I wonder whether the pictures in the "scannet_normal" and "matterport_normal" folders are the result pictures after the DeepCompletion step?
 Thank you very much if you can give me any help!
