### ISSUE TITLE
One example of the train dataset

### ISSUE THREAD

**Issue by eli2014** [yindaz/DeepCompletionRelease#17]
I'm preparing for training on my own data, but I don't know what is the correct format of the training example. Could you please post one example of the training data? 
That is, surface normal part:
1. color image
2. mesh_nx.png
3. mesh_ny.png
4. mesh_nz.png
5. raw_depth.png
6. mesh_depth.png

occlusion boundary part:
1. _mlt.png
2. _valid.png
3. _3d_boundary.png

Thanks for your excellent job!

**Comment by yindaz** [comment]
We've shared the training data. You should be able to find a lot of examples over there. Thanks.
