### ISSUE TITLE
evalDepth.m

### ISSUE THREAD

**Issue by SunshineDou** [yindaz/DeepCompletionRelease#18]
@yindaz hello,
Could you please tell me what should I do if I want to evaluate on my own dataset result? in the evalDepth.m file, there are two lines as follows:
raw = testdata(a).raw;
gdt = testdata(a).gdt;

the raw is the original data, right? but what's the gdt? how to get it?
I have also download the "scannet_normal" and "matterport_normal" in the pre_calc_result folder, I wonder whether the pictures in the "scannet_normal" and "matterport_normal" folders are the result pictures after the DeepCompletion step?
Thank you very much!

**Comment by yindaz** [comment]
raw is the sensor depth, i.e. the bad depth. gdt is the ground truth depth, i.e. the complete depth.

Files in those folders should be the output of network.
