### ISSUE TITLE
normal estimation

### ISSUE THREAD

**Issue by Mikeraka** [yindaz/DeepCompletionRelease#19]
@yindaz Hello, When I run the dem_realsense.m, I ran into a problem as follows:
![2019-03-01 10-41-39](https://user-images.githubusercontent.com/45626438/53537968-cfb4e880-3b46-11e9-8085-7ed605d9fa67.png)

I find that it's because of the normal estimation, when estimating the normal, it will be out of memory if the data was larger than 50, it can only generate about 30 pictures in the normal estimation step. I am wondering about how to modify it, Could you please give me some suggestion? Thank you very much

**Comment by yindaz** [comment]
The memory shouldn't go with the number of images, and 50 images are not too much. What GPU are you using? I ran this script on a set of data with 500 images, and it was fine.
