### ISSUE TITLE
Why is weight*1000 saved as uint16 images?

### ISSUE THREAD

**Issue by hyf015** [yindaz/DeepCompletionRelease#2]
Hi,
I read your paper and like your work very much. When I was trying to read your code, I found this line:
https://github.com/yindaz/DeepCompletionRelease/blob/922fc064bb8f480be1d8b31a1b8755eaea8fb268/matlab/GenerateOcclusionWeight.m#L14

If I understand correctly, in matlab MaxValue for uint16 images is 65535. May I know what's the point of weight*1000 here?

**Comment by yindaz** [comment]
You are correct this does not saturate the uint16 value range. This is just to reuse the image reading function that accepts 16bit PNG and usually 10^-3 accuracy is sufficient for optimization.

**Comment by hyf015** [comment]
Thank you for your answer. I'll look into it.
