### ISSUE TITLE
What is the average forward time during inference?

### ISSUE THREAD

**Issue by Guptajakala** [yindaz/DeepCompletionRelease#20]
Hi, First thanks for sharing the code.
May I ask what is the average forward time during inference? This seems not mentioned in paper.

**Comment by yindaz** [comment]
We didn't optimize the network capacity yet, and there should be a lot to squeeze. It takes something less than 1 sec to test in our implementation, but that's not very useful data point any way. I believe this can be optimized to run really fast.
