### ISSUE TITLE
bad argument #1 to 'sub' (string expected, got nil)

### ISSUE THREAD

**Issue by wuheng199112068** [yindaz/DeepCompletionRelease#21]
/home/BH/by1706143/torch/install/bin/lua: main_test_bound_matterport.lua:21: bad argument #1 to 'sub' (string expected, got nil)
stack traceback:
	[C]: in function 'sub'
	main_test_bound_matterport.lua:21: in main chunk
	[C]: in function 'dofile'
	...6143/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

**An error occurred while running. What is the cause** thank you

**Comment by yindaz** [comment]
I guess you didn't give the correct list file.
