### ISSUE TITLE
The code will stop here, and it won't work. Why?

### ISSUE THREAD

**Issue by wuheng199112068** [yindaz/DeepCompletionRelease#23]
Loading data from ./data_list/scannet_test_list.txt 5 data loaded.
500 data loaded.

![cb10057c1fda6bf2d43d84680de0233](https://user-images.githubusercontent.com/34667465/54484693-605d2980-48a6-11e9-91ff-d54e18435075.png)

**Comment by yindaz** [comment]
The root path is clearly wrong. It cannot find files, I guess.

**Comment by Darker-zq** [comment]
@wuheng199112068 Do you have any datasets provided by the author? If so, please send me a copy.Thaks!
My Email is [01170218@cumt.edu.cn](mailto:01170218@cumt.edu.cn)
