### ISSUE TITLE
Is unit of depth matters?

### ISSUE THREAD

**Issue by YongjianDeng** [yindaz/DeepCompletionRelease#25]
Hi,

I am trying to apply your noticed method on my own data using the pretrained model directly. I noticed that in the Readme file you have mentioned that the unit of  input and output depth image  value should be 4000 x depth in meter, can I use 1000 x depth in meter as input image, i.e 1000 in depth map when the real depth is 1 meter. will this different unit of input effect the performance of the pretrained model?

**Comment by yindaz** [comment]
It matters. It will affect the consistency between the depth and the surface normal, under the given intrinsic matrix.

**Comment by YongjianDeng** [comment]
Thanks for your comment, I'll have a try by changing the unit of depth.
