### ISSUE TITLE
Is it available to use 16:9 input image? 

### ISSUE THREAD

**Issue by dontknowwhattoname** [yindaz/DeepCompletionRelease#27]
I have seen the #12 and I use the method of up sampling when I need higher resolution input image. But what should I do if I what to use 16:9 input image.Can I edit some parameters to solve this or the only way is to retrain the model? Thank you!

**Comment by yindaz** [comment]
The model is a fully convolutional network, which is adaptive to various input size and aspect ratio.

**Comment by Darker-zq** [comment]
@dontknowwhattoname Do you have any datasets provided by the author? If so, please send me a copy.Thaks!
My Email is [01170218@cumt.edu.cn](mailto:01170218@cumt.edu.cn)
