### ISSUE TITLE
Input Format

### ISSUE THREAD

**Issue by roxanneluo** [yindaz/DeepCompletionRelease#3]
Can you help specify the input format?
For depth, how do you specify the holes?
For normals, is each pixel of value (nx, ny, nz) \in [-1,1] ^3?
For occlusion boundary, how to you save the probability? You said it's saved as .png, but I suppose the probability is float while png files stores int.

**Comment by yindaz** [comment]
Hi,

I recommend you to run the demo for these details. The demo is well documented and easy to understand. Also, you may find many of these details in gaps and surface normal related codes. Please see below for quick answers to your questions:

Can you help specify the input format?
-- The input depths are in 16bit PNG, encoding depth in mm times 4000. 
For depth, how do you specify the holes?
-- The missing area will have a depth value of 0
For normals, is each pixel of value (nx, ny, nz) \in [-1,1] ^3?
-- Yes
For occlusion boundary, how to you save the probability? You said it's saved as .png, but I suppose the probability is float while png files stores int.
-- We use 16-bit PNG, which maps 0-1 into 0-65535. It is true that there can be some quantization error, but numerically almost invisible.
