### ISSUE TITLE
something wrong with my own depth map

### ISSUE THREAD

**Issue by h1063135843** [yindaz/DeepCompletionRelease#42]
I run the demo successfully, and the result looks good.But when I test my own depth map, it seems the program doesn't work. The following picture is the result shown in the matlab.
![图片](https://user-images.githubusercontent.com/26903569/100573607-28647700-3313-11eb-8ab3-2d2adc12fdce.png)
And this is the input color.
![图片](https://user-images.githubusercontent.com/26903569/100573722-6b264f00-3313-11eb-92f8-49a9b674cf12.png)
Another example:
![图片](https://user-images.githubusercontent.com/26903569/100573795-9610a300-3313-11eb-8c91-1f7491d4bdc4.png)
![图片](https://user-images.githubusercontent.com/26903569/100573826-a6c11900-3313-11eb-863f-c4dfcea63653.png)
The result is obviously incorrect. What's the reason? And how can I solve it?
The depth sensor is azure kinect.

**Comment by jiunyen-ching** [comment]
From the input images, it looks like there are some pixels with values close to zero at the border of the white mask. So (I think) the region with missing depth will be affected by these pixels during inference.

**Comment by h1063135843** [comment]
> From the input images, it looks like there are some pixels with values close to zero at the border of the white mask. So (I think) the region with missing depth will be affected by these pixels during inference.

Thanks a lot. You are right! To meet the requirement of memory size, I downsample the depth map. And it's the reason why those pixels near boundary with values close to zero occur.

**Comment by ZzzBHD** [comment]
So how you solve this problem？Use the original depth maps？Since I use the Azure Kinect either.

**Comment by h1063135843** [comment]
> So how you solve this problem？Use the original depth maps？Since I use the Azure Kinect either.

make those depth lower than some threshold to zero.

**Comment by jiunyen-ching** [comment]
@ZzzBHD Thresholding to zero as @h1063135843 suggested is one way to do it because the algorithm accepts values at 0 as the inpainting-mask. Alternatively, you can prepare a mask at full resolution, dilate the mask then downsample the mask to your needed resolution.

**Comment by ZzzBHD** [comment]
> > So how you solve this problem？Use the original depth maps？Since I use the Azure Kinect either.
> 
> make those depth lower than some threshold to zero.

Thanks a lot！I will try this, and look forward to getting your help if I meet problems again

**Comment by Darker-zq** [comment]
@h1063135843  Do you have any datasets provided by the author? If so, please send me a copy.Thaks!
My Email is 01170218@cumt.edu.cn

**Comment by Spero-felix** [comment]
> @h1063135843 Do you have any datasets provided by the author? If so, please send me a copy.Thaks! My Email is [01170218@cumt.edu.cn](mailto:01170218@cumt.edu.cn)

Do you have the datasets? if so, can you send to my email?
My email is [whznsphjhj@gmail.com](url)
