### ISSUE TITLE
can not compile because hdf5.h

### ISSUE THREAD

**Issue by DiscoDiscoBoomBoom** [yindaz/DeepCompletionRelease#5]
fatal error: hdf5.h: No such file or directory

**Comment by xjtucx** [comment]
> I fix the problem by rewirte the makefile.std,and add the location of hdf5.

can you tell me how to add the location of hdf5?thanks

**Comment by DiscoDiscoBoomBoom** [comment]
@xjtucx you should read https://github.com/tomfunkhouser/gaps carefully,and add your hdf5 location.

**Comment by xjtucx** [comment]
> @xjtucx you should read https://github.com/tomfunkhouser/gaps carefully,and add your hdf5 location.

sorry,i have read this but i don't know where should i add my hdf5 location.I have no idea to rewrite the makefile.std.Could you give me more details?

**Comment by SunshineDou** [comment]
@DiscoDiscoBoomBoom hello, I have also run into this problem, and as I am not very familiar with this, could you please show me the makefile.std and makefile.apps that you have modified? I really don't know how to modify it. Thank you very much

**Comment by SunshineDou** [comment]
@DiscoDiscoBoomBoom I have added the hdf5/include to the makefile.std and add your hdf5/lib to the makefile.apps as follows, but it still report errors
![hdf5](https://user-images.githubusercontent.com/25578572/50054072-fafb7e80-0178-11e9-8fd7-fa85e6bd4b19.png)
![hdf5_2](https://user-images.githubusercontent.com/25578572/50054073-fcc54200-0178-11e9-8bec-e30af9af5169.png)
what's wrong? Thank you very much

**Comment by SunshineDou** [comment]
I have solved it

**Comment by Mrxiashu** [comment]
@SunshineDou  I want to know how you solved it.thank you！

**Comment by SunshineDou** [comment]
@Mrxiashu 
I use this command to add it into the environment first
export CPATH="/usr/include/hdf5/serial/" 
Then I modify the makefile as follows:
'USER_LIBS=-lhdf5'——>USER_LIBS = -L/usr/include/hdf5/serial/ -lhdf5
finally,type'make clean' and 'make'

**Comment by yipingp** [comment]
> @Mrxiashu
> I use this command to add it into the environment first
> export CPATH="/usr/include/hdf5/serial/"
> Then I modify the makefile as follows:
> 'USER_LIBS=-lhdf5'——>USER_LIBS = -L/usr/include/hdf5/serial/ -lhdf5
> finally,type'make clean' and 'make'

Hi, adding CPATH... to environment works for me. 
However, after modifying makefile as same as you do, the problem "can not find -lhdf5" still happens.
Then, I modify your code to 
USER_LIBS = -usr/include/hdf5/serial/lhdf5
errors arise as follows:
depth2depth.cpp:(.text+0xdde)：Undefined reference to 'H5check_version'
depth2depth.cpp:(.text+0xde3)：Undefined reference to 'H5open'
...

Could you please tell me how to fix this? Thanks a lot!!

**Comment by huzhlei** [comment]
@timeperiod 
In my case, no new lines in Makefile.std or Makefile.apps are added. 
Besides adding CPATH..., I modify 'USER_LIBS=-lhdf5' to 
'USER_LIBS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib -lhdf5'. 
The path after -L is where libhdf5.so locates. -L indicated linking to the library.
Our paths could be of some difference. Maybe this file list of package libhdf5-dev (https://packages.ubuntu.com/bionic/amd64/libhdf5-dev/filelist) could be some reference to you.

**Comment by yipingp** [comment]
@huzhlei 
 Thanks to your detailed explanation, I figure it out! Thank you!!!

**Comment by nonlinear1** [comment]
@huzhlei 
I am sorry to trouble you, but I have no idear,could you help me?
I have do the below things,but it not work,do I have something wrong? I am sure thar the libhdf5.so path is right.
1.export CPATH="/usr/include/hdf5/serial/"
2. add USER_LIBS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib -lhdf5 to makefile.apps
as follows:
============================
#OPENGL_LIBS=-lglut -lGLU -lGL -lX11 -lm
#OPENGL_LIBS=-pthread -lfglut -lGLU -lGL -lX11 -lm
OPENGL_LIBS=-pthread -lGLU -lGL -lX11 -lm
endif
USER_LIBS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial/lib -lhdf5   ※※※this line is added by me.
LIBS=$(PKG_LIBS) $(USER_LIBS) $(OPENGL_LIBS)
============================
