### ISSUE TITLE
depth2depth.cpp:11:18: fatal error: hdf5.h: No such file or directory

### ISSUE THREAD

**Issue by name333** [yindaz/DeepCompletionRelease#6]
depth2depth.cpp:11:18: fatal error: hdf5.h: No such file or directory.
How could I solve this problem? Could you give me a ｈｄf5.h file?
Thank a lot!

**Comment by rohun-tripathi** [comment]
Does installing hdf5 help?
For example, this issue seems to occur when using caffe as well and they fix as - https://ahmedibrahimvt.wordpress.com/2017/02/19/fatal-error-hdf5-h-no-such-file-or-directory/ and  https://stackoverflow.com/questions/37007495/caffe-didnt-see-hdf5-h-when-compiling

**Comment by yindaz** [comment]
Please check this closed issue: https://github.com/yindaz/DeepCompletionRelease/issues/5
