### ISSUE TITLE
Port optimization code to python

### ISSUE THREAD

**Issue by rohun-tripathi** [yindaz/DeepCompletionRelease#7]
Thanks for your work!
I want to port the global optimizer to python to use it for a similar task. Do you know of any python bindings for sparse solvers that I can use, or of any codebase already out there doing something similar?

**Comment by yindaz** [comment]
Sorry I am not familiar with Python on this. But our linear optimization is quite standard, and I believe most of the package solving linear system can do the job. Thanks.

**Comment by rohun-tripathi** [comment]
Thanks, I used the scipy.sparse.linalg.lsmr to solve it in python. Did you experiment with different relative weights (lamda_d and lamda_s in your paper) for the normals and the depth error components during the optimization and if so, what was your final configuration?

**Comment by yindaz** [comment]
Please see weights in demo: https://github.com/yindaz/DeepCompletionRelease/blob/master/matlab/demo_realsense.m

Thanks!

**Comment by rohun-tripathi** [comment]
Thanks for the link to the weights. I was wondering - how much does the weight for keeping the adjacent pixels at the same depth help?
I tried using the system with that weight set to 0 and obtained patchy images. Have you encountered a similar output?

**Comment by fuxiao567** [comment]
> 感谢您的工作！
> 我想将全局优化器移植到python，以将其用于类似的任务。您是否知道我可以使用的任何用于稀疏求解器的python绑定，或者已经存在的任何类似代码库在做类似的事情？



> Thanks for your work!
> I want to port the global optimizer to python to use it for a similar task. Do you know of any python bindings for sparse solvers that I can use, or of any codebase already out there doing something similar?

Have you finished this work?

**Comment by Chen94yue** [comment]
> Thanks for the link to the weights. I was wondering - how much does the weight for keeping the adjacent pixels at the same depth help? I tried using the system with that weight set to 0 and obtained patchy images. Have you encountered a similar output?

Have you finished this work?

**Comment by JiePaiWs** [comment]
> Thanks, I used the scipy.sparse.linalg.lsmr to solve it in python. Did you experiment with different relative weights (lamda_d and lamda_s in your paper) for the normals and the depth error components during the optimization and if so, what was your final configuration?

Hello,thanks for your work.I wonder whether you have finished the work ? Best wishes to you.
