### ISSUE TITLE
cannot load '/home/user/torch/install/lib/lua/5.1/libcutorch.so'

### ISSUE THREAD

**Issue by ccyinlu** [yindaz/DeepCompletionRelease#8]
```
/home/hy/torch/install/bin/luajit: /home/hy/torch/install/share/lua/5.1/trepl/init.lua:389: /home/hy/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '/home/hy/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:
        [C]: in function 'error'
        /home/hy/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        main_test_bound_realsense.lua:2: in main chunk
        [C]: in function 'dofile'
        ...e/hy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
/home/hy/torch/install/bin/luajit: /home/hy/torch/install/share/lua/5.1/trepl/init.lua:389: /home/hy/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '/home/hy/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:
        [C]: in function 'error'
        /home/hy/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        main_test_realsense.lua:2: in main chunk
        [C]: in function 'dofile'
        ...e/hy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
```

when run the demo `demo_realsense.m` under the directory `./matlab`, I was confronted the problem as described above. I've checked the torch environment and installed `cuda` and `cudnn` for torch, the error still existed.  

When I run the command `th main_test_bound_realsense.lua -test_model ../pre_train_model/bound.t7 -test_file ./data_list/realsense_list.txt -root_path ../data/realsense/` outside matlab, it all went well, so I guess it is the problem related to matlab.  

I've searched on the web and found a similar question: `https://github.com/pytorch/pytorch/issues/7082` .

Is there any solution for this problem? Thanks a lot!

**Comment by yindaz** [comment]
I believe this is not the problem of my code, but the failure of loading some library in your system. Find those libraries and add their paths to LD_LIBRARY_PATH.
