### ISSUE TITLE
Using 16-bit PNG

### ISSUE THREAD

**Issue by shgold** [yindaz/DeepCompletionRelease#9]
Hello, 

I appreciate you releasing your work, and it is exciting to try them out. 
However, I wonder what the reason behind multiplying 4000 to depth in mm is. 
I have tried multiplying different values, and it still seems work. 

Could you explain why you have chosen this specific value(4000) for multiplication?

Bests,
Stella

**Comment by yindaz** [comment]
Hi Stella,

We used 16-bit png to save depth. As indoor depth usually ranges from 0-15m, timing the depth by 4000 makes good use of the 16bit range, i.e. 0-65535. 

Multiply 1000 will likely to get our code work visually, but numerically wrong as the depth has to be work with the intrinsic matrix.
